import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Got Radio The 60's",
            artist: "60's",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://pureplay.cdnstream1.com/6011_128.mp3",
            active: true,
        },
        {
            name:"Vida Eterna",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_81741_Emisora Palabra De Vida Eterna Radio.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://cloudstream2030.conectarhosting.com:10974/;",
            active: true,
        },
        {
            name:"Radio Fe y Armonía",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_12710_Radio Fe y Armonía.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://cloudstream2036.conectarhosting.com/8116/stream",
            active: true,
        },
        {
            name:"Radio Pentecostal",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_58208_Radio Pentecostal.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-42.zeno.fm/pq4vu73qeuhvv?zs=",
            active: true,
        },
        {
            name:"Christian Passion",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_68266_Christian Passion.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-26.zeno.fm/wm9ukzeruzzuv?zs=",
            active: true,
        },
        {
            name:"Radio Verbo",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_96760_Radio Verbo.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-59.zeno.fm/8c7ke88c0s8uv?zs=",
            active: true,
        },
        {
            name:"ETD Radio (Es tiempo de Dios)",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_43406_ETD Radio (Es tiempo de Dios).png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-40.zeno.fm/vgywt7w6608uv?zs=",
            active: true,
        },
        {
            name:"Conexion Vertical",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_97643_Conexion Vertical.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://163.172.77.142:8372/;",
            active: true,
        },
        {
            name:"Radio La Verdad Del Evangelio",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_17609_Radio La Verdad Del Evangelio.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-64.zeno.fm/27v91uzrbv8uv?zs=",
            active: true,
        },
        {
            name:"Radio Elohim",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_75481_Radio Elohim.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-54.zeno.fm/b53kvuaadkhvv?zs=",
            active: true,
        },
        {
            name:"Kadosh Radio",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_64533_Kadosh Radio.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://radio35.virtualtronics.com/proxy/kadoshradio?mp=%2Fstream",
            active: true,
        },
        {
            name:"Radio Nación Santa",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_80515_Radio Nación Santa.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://streamprivate.live/8002/stream",
            active: true,
        },
        {
            name:"Ministerio Radial ICRJ",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_28341_Ministerio Radial ICRJ.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-41.zeno.fm/rhzba1duqp8uv?zs=",
            active: true,
        },
        {
            name:"JG Radio",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_11681_JG Radio.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-44.zeno.fm/zwfymafk4ehvv?zs=",
            active: true,
        },
        {
            name:"Radio Misión celestial",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_63885_Radio Misión celestial.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://95.111.251.90:8203/;",
            active: true,
        },
        {
            name:"Hits for Kids",
            artist: "Kids",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s1-webradio.antenne.de/hits-fuer-kids/stream/mp3?aw_0_1st.playerid=tunein.com",
            active: false,
        },
    ];
}

export default chillHop;

