import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [
        
        {
            name:"Su Presencia",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_81399_Su Presencia.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://supresenciaradio.out.airtime.pro:8000/supresenciaradio_a",
            active: true,
        },
        {
            name:"Cadena Radial Vida - Pereira 1120 AM",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_26897_Cadena Radial Vida - Pereira 1120 AM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://26273.live.streamtheworld.com/VIDA_BOGOTA_SC?dist=onlineradiobox",
            active: true,
        },
        {
            name:"Radio Cristiana Caminando Con Dios",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_90826_Radio Cristiana Caminando Con Dios.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-11.zeno.fm/yyday44d508uv?zs=",
            active: true,
        },
        {
            name:"Pasion Cristiana",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_72821_Pasion Cristiana.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-17.zeno.fm/mzs0x146ctzuv?zs=",
            active: true,
        },
        {
            name:"Pasion Instrumental",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_38714_Pasion Instrumental.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-16.zeno.fm/f0vta0y651zuv?zs=",
            active: true,
        },
        {
            name:"Santa Biblia",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_79495_Santa Biblia.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-37.zeno.fm/856q8t4quzzuv?zs=",
            active: true,
        },
        {
            name:"Cristianos Radio",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_96001_Cristianos Radio.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://emisorasvirtuales.com.co:9489/live",
            active: true,
        },
        {
            name:"Predicas Armando Alducin",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_8603_Predicas Armando Alducin.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-25.zeno.fm/sqb5ahue21zuv?zs=",
            active: true,
        },
        {
            name:"La Voz de Jesús",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_81828_La Voz de Jesús.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-62.zeno.fm/phybdd3ph98uv?zs=",
            active: true,
        },
        {
            name:"Radio Epiayu Stereo",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_75962_Radio Epiayu Stereo.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://dattavolt.com:7195/;",
            active: true,
        },
        {
            name:"Tropisalsa Cristiana",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_95866_Tropisalsa Cristiana.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-29.zeno.fm/t4y7f2ev88quv?zs=",
            active: true,
        },
        {
            name:"ENC Radio (Nuevo Continente)",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_14312_ENC Radio (Nuevo Continente).png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://99.198.110.162:7092/;",
            active: true,
        },
        {
            name:"Vitrola Cristiana",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_62341_Vitrola Cristiana.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-17.zeno.fm/qyuc60d0gnruv?zs=",
            active: true,
        },
        {
            name:"Radio Uno en Cristo",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_22335_Radio Uno en Cristo.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-59.zeno.fm/wupqqzar0wzuv?zs=",
            active: true,
        },
        {
            name:"Aviva2",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_22040_Aviva2.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream.avivamientoradio.net/radio/8000/radio.mp3",
            active: true,
        },
        {
            name:"Emisora Palabra De Vida Eterna Radio",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_58115_Emisora Palabra De Vida Eterna Radio.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://play14.tikast.com:22046/;",
            active: true,
        },
        {
            name:"Abba Padre Radios",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_79749_Abba Padre Radios.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://emisorasvirtuales.com.co:9402/live",
            active: true,
        },
        {
            name:"Chat y Radio Cristiana en Bogota Colombia en Linea de Periodista Cristiano",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_30432_Chat y Radio Cristiana en Bogota Colombia en Linea de Periodista Cristiano.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-42.zeno.fm/un9we3zwvd0uv?zs=",
            active: true,
        },
        {
            name:"Radio Cristo Ya Viene",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_66770_Radio Cristo Ya Viene.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-51.zeno.fm/brkbygrf3rquv?zs=",
            active: true,
        },
        {
            name:"Capsulas de la Biblia",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_52754_Capsulas de la Biblia.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-10.zeno.fm/1mypu8b9zmzuv?zs=",
            active: true,
        },
        {
            name:"Casa de Dios Sobrenatural
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_87269_Casa de Dios Sobrenatural.png
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://radio35.virtualtronics.com/proxy/casadediossobrenatural?mp=%2Fstream
            active: true,
        },
        {
            name:"Tropiradio",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_24751_Tropiradio.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://radiolatina.info:9854/;",
            active: true,
        },
        {
            name:"Instituto Biblico Izamar",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_1558_Instituto Biblico Izamar.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-36.zeno.fm/r6mh3b9mxmzuv?zs=",
            active: true,
        },
        {
            name:"VPC - Voz de la Patria Celestial",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_9922_VPC - Voz de la Patria Celestial.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://149.56.147.197:8004/stream",
            active: true,
        },
        {
            name:"Su Reino Stereo",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_95156_Su Reino Stereo.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://51.15.160.78:8070/;",
            active: true,
        },
        {
            name:"Palabra Pura",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_19399_Palabra Pura.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-61.zeno.fm/5e08f76251zuv?zs=",
            active: true,
        },
        {
            name:"Bendicion Radio",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_32037_Bendicion Radio.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://streamingmediaradio.live/8092/stream",
            active: true,
        },
        {
            name:"Radio Promesa Estereo",
            artist: "Musica Cristiana",
            cover: "https://dab-radios.org/admin_panel_crisradiocolombia/uploads/radios/radio_98972_Radio Promesa Estereo.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://radio30.virtualtronics.com:8228/stream",
            active: true,
        },
        {
            name:"Hits for Kids",
            artist: "Kids",
            cover: "https://png.pngtree.com/png-vector/20190726/ourlarge/pngtree-modern-square-cool-music-for-party-lights-png-image_1629696.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "http://s1-webradio.antenne.de/hits-fuer-kids/stream/mp3?aw_0_1st.playerid=tunein.com",
            active: false,
        },
    ];
}

export default chillHop;

